// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/herocwhsu/training/utexample/internal/company/domain"
	domain0 "github.com/herocwhsu/training/utexample/internal/membership/domain"
	interfaces "github.com/herocwhsu/training/utexample/internal/membership/interfaces"
	domain1 "github.com/herocwhsu/training/utexample/internal/user/domain"
)

// MockCompanyReader is a mock of CompanyReader interface.
type MockCompanyReader struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyReaderMockRecorder
}

// MockCompanyReaderMockRecorder is the mock recorder for MockCompanyReader.
type MockCompanyReaderMockRecorder struct {
	mock *MockCompanyReader
}

// NewMockCompanyReader creates a new mock instance.
func NewMockCompanyReader(ctrl *gomock.Controller) *MockCompanyReader {
	mock := &MockCompanyReader{ctrl: ctrl}
	mock.recorder = &MockCompanyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyReader) EXPECT() *MockCompanyReaderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockCompanyReader) FindByID(ctx context.Context, id string) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCompanyReaderMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCompanyReader)(nil).FindByID), ctx, id)
}

// MockUserReader is a mock of UserReader interface.
type MockUserReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserReaderMockRecorder
}

// MockUserReaderMockRecorder is the mock recorder for MockUserReader.
type MockUserReaderMockRecorder struct {
	mock *MockUserReader
}

// NewMockUserReader creates a new mock instance.
func NewMockUserReader(ctrl *gomock.Controller) *MockUserReader {
	mock := &MockUserReader{ctrl: ctrl}
	mock.recorder = &MockUserReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReader) EXPECT() *MockUserReaderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockUserReader) FindByID(ctx context.Context, id string) (*domain1.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserReaderMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserReader)(nil).FindByID), ctx, id)
}

// MockMembershipRepository is a mock of MembershipRepository interface.
type MockMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepositoryMockRecorder
}

// MockMembershipRepositoryMockRecorder is the mock recorder for MockMembershipRepository.
type MockMembershipRepositoryMockRecorder struct {
	mock *MockMembershipRepository
}

// NewMockMembershipRepository creates a new mock instance.
func NewMockMembershipRepository(ctrl *gomock.Controller) *MockMembershipRepository {
	mock := &MockMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepository) EXPECT() *MockMembershipRepositoryMockRecorder {
	return m.recorder
}

// ExistsByCompanyAndUser mocks base method.
func (m *MockMembershipRepository) ExistsByCompanyAndUser(ctx context.Context, companyID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCompanyAndUser", ctx, companyID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCompanyAndUser indicates an expected call of ExistsByCompanyAndUser.
func (mr *MockMembershipRepositoryMockRecorder) ExistsByCompanyAndUser(ctx, companyID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCompanyAndUser", reflect.TypeOf((*MockMembershipRepository)(nil).ExistsByCompanyAndUser), ctx, companyID, userID)
}

// FindByCompanyID mocks base method.
func (m *MockMembershipRepository) FindByCompanyID(ctx context.Context, companyID string) ([]*domain0.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCompanyID", ctx, companyID)
	ret0, _ := ret[0].([]*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCompanyID indicates an expected call of FindByCompanyID.
func (mr *MockMembershipRepositoryMockRecorder) FindByCompanyID(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCompanyID", reflect.TypeOf((*MockMembershipRepository)(nil).FindByCompanyID), ctx, companyID)
}

// FindByID mocks base method.
func (m *MockMembershipRepository) FindByID(ctx context.Context, id string) (*domain0.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMembershipRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMembershipRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockMembershipRepository) FindByUserID(ctx context.Context, userID string) ([]*domain0.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockMembershipRepositoryMockRecorder) FindByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockMembershipRepository)(nil).FindByUserID), ctx, userID)
}

// Remove mocks base method.
func (m *MockMembershipRepository) Remove(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMembershipRepositoryMockRecorder) Remove(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMembershipRepository)(nil).Remove), ctx, id)
}

// Save mocks base method.
func (m_2 *MockMembershipRepository) Save(ctx context.Context, m *domain0.Membership) (*domain0.Membership, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockMembershipRepositoryMockRecorder) Save(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMembershipRepository)(nil).Save), ctx, m)
}

// MockMembershipDAO is a mock of MembershipDAO interface.
type MockMembershipDAO struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipDAOMockRecorder
}

// MockMembershipDAOMockRecorder is the mock recorder for MockMembershipDAO.
type MockMembershipDAOMockRecorder struct {
	mock *MockMembershipDAO
}

// NewMockMembershipDAO creates a new mock instance.
func NewMockMembershipDAO(ctrl *gomock.Controller) *MockMembershipDAO {
	mock := &MockMembershipDAO{ctrl: ctrl}
	mock.recorder = &MockMembershipDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipDAO) EXPECT() *MockMembershipDAOMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockMembershipDAO) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockMembershipDAOMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockMembershipDAO)(nil).DeleteByID), ctx, id)
}

// ExistsByCompanyAndUser mocks base method.
func (m *MockMembershipDAO) ExistsByCompanyAndUser(ctx context.Context, companyID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCompanyAndUser", ctx, companyID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCompanyAndUser indicates an expected call of ExistsByCompanyAndUser.
func (mr *MockMembershipDAOMockRecorder) ExistsByCompanyAndUser(ctx, companyID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCompanyAndUser", reflect.TypeOf((*MockMembershipDAO)(nil).ExistsByCompanyAndUser), ctx, companyID, userID)
}

// FindByCompanyID mocks base method.
func (m *MockMembershipDAO) FindByCompanyID(ctx context.Context, companyID string) ([]interfaces.MembershipRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCompanyID", ctx, companyID)
	ret0, _ := ret[0].([]interfaces.MembershipRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCompanyID indicates an expected call of FindByCompanyID.
func (mr *MockMembershipDAOMockRecorder) FindByCompanyID(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCompanyID", reflect.TypeOf((*MockMembershipDAO)(nil).FindByCompanyID), ctx, companyID)
}

// FindByID mocks base method.
func (m *MockMembershipDAO) FindByID(ctx context.Context, id string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMembershipDAOMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMembershipDAO)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockMembershipDAO) FindByUserID(ctx context.Context, userID string) ([]interfaces.MembershipRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]interfaces.MembershipRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockMembershipDAOMockRecorder) FindByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockMembershipDAO)(nil).FindByUserID), ctx, userID)
}

// Insert mocks base method.
func (m *MockMembershipDAO) Insert(ctx context.Context, companyID, userID, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, companyID, userID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockMembershipDAOMockRecorder) Insert(ctx, companyID, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMembershipDAO)(nil).Insert), ctx, companyID, userID, role)
}

// MockMembershipService is a mock of MembershipService interface.
type MockMembershipService struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipServiceMockRecorder
}

// MockMembershipServiceMockRecorder is the mock recorder for MockMembershipService.
type MockMembershipServiceMockRecorder struct {
	mock *MockMembershipService
}

// NewMockMembershipService creates a new mock instance.
func NewMockMembershipService(ctrl *gomock.Controller) *MockMembershipService {
	mock := &MockMembershipService{ctrl: ctrl}
	mock.recorder = &MockMembershipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipService) EXPECT() *MockMembershipServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMembershipService) Add(ctx context.Context, companyID, userID, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, companyID, userID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockMembershipServiceMockRecorder) Add(ctx, companyID, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMembershipService)(nil).Add), ctx, companyID, userID, role)
}

// ListByCompany mocks base method.
func (m *MockMembershipService) ListByCompany(ctx context.Context, companyID string) ([]*domain0.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCompany", ctx, companyID)
	ret0, _ := ret[0].([]*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCompany indicates an expected call of ListByCompany.
func (mr *MockMembershipServiceMockRecorder) ListByCompany(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCompany", reflect.TypeOf((*MockMembershipService)(nil).ListByCompany), ctx, companyID)
}

// ListByUser mocks base method.
func (m *MockMembershipService) ListByUser(ctx context.Context, userID string) ([]*domain0.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*domain0.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockMembershipServiceMockRecorder) ListByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockMembershipService)(nil).ListByUser), ctx, userID)
}

// Remove mocks base method.
func (m *MockMembershipService) Remove(ctx context.Context, membershipID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, membershipID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMembershipServiceMockRecorder) Remove(ctx, membershipID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMembershipService)(nil).Remove), ctx, membershipID)
}
